// <auto-generated />
namespace NexusAsistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nullTimespam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullTimespam));
        
        string IMigrationMetadata.Id
        {
            get { return "202108230237569_nullTimespam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
